// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAwXxy3UIPTzV7JHmgBbVKzuWHU-wsKa4',
    appId: '1:1016540886778:web:f09d71d458516a952c7b43',
    messagingSenderId: '1016540886778',
    projectId: 'crm-leave-management',
    authDomain: 'crm-leave-management.firebaseapp.com',
    storageBucket: 'crm-leave-management.firebasestorage.app',
    measurementId: 'G-7JVRX3VRDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnRCHN1BzhHPt6WEDYQWNCjy5MOezFoc',
    appId: '1:1016540886778:android:719fc5d64b1b44f22c7b43',
    messagingSenderId: '1016540886778',
    projectId: 'crm-leave-management',
    storageBucket: 'crm-leave-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1BHVEQvZFZLl1e8VkE_iKmJE0Kae8DI',
    appId: '1:1016540886778:ios:aa3c0ea5848a79c42c7b43',
    messagingSenderId: '1016540886778',
    projectId: 'crm-leave-management',
    storageBucket: 'crm-leave-management.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK1BHVEQvZFZLl1e8VkE_iKmJE0Kae8DI',
    appId: '1:1016540886778:ios:aa3c0ea5848a79c42c7b43',
    messagingSenderId: '1016540886778',
    projectId: 'crm-leave-management',
    storageBucket: 'crm-leave-management.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAwXxy3UIPTzV7JHmgBbVKzuWHU-wsKa4',
    appId: '1:1016540886778:web:65a57fd80077399c2c7b43',
    messagingSenderId: '1016540886778',
    projectId: 'crm-leave-management',
    authDomain: 'crm-leave-management.firebaseapp.com',
    storageBucket: 'crm-leave-management.firebasestorage.app',
    measurementId: 'G-KQ9RE0ZNER',
  );
}
